version: 3
tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build application
    cmds:
      - rm -rf dist/ && mkdir dist/
      - go build -o ./dist/ ./cmd/failbook

  # builds a fully static Linux binary of Go application
  # - CGO_ENABLED=0 disables CGO for full static linking
  # - GOOS=linux targets Linux (cross-compilation if needed)
  # - -a rebuilds all packages
  # - -installsuffix cgo separates CGO-disabled build artifacts from any CGO-enabled ones
  # - -ldflags '-extldflags "-static"' ensures the binary is statically linked (no libc dependency)
  # - -o failbook sets the output binary name
  build-prod:
    desc: Build application for production
    cmds:
      - rm -rf dist/ && mkdir dist/
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o ./dist/ ./cmd/failbook

  build-docker:
    desc: Build malczuuu/failbook:latest Docker image
    # If failbook-builder:latest image does not exists, it builds it as well.
    cmds:
      - |
        if ! docker image inspect failbook-builder:latest >/dev/null 2>&1; then
          echo "[INFO] Builder image not found. Building taskbook-builder:latest ..."
          docker build -f Dockerfile.builder -t failbook-builder:latest .
        fi
        docker build -f Dockerfile -t malczuuu/failbook:latest .
