version: 3
tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build application
    cmds:
      - rm -rf dist/ && mkdir dist/
      - go build -o ./dist/ ./cmd/failbook
